import { Template } from "@pdfme/generator";
export const schemasFull: Template["schemas"] = [
  {
    transport: {
      type: "text",
      position: {
        x: 25.14,
        y: 85.46,
      },
      width: 85.01,
      height: 23.13,
      alignment: "left",
      fontSize: 10,
      characterSpacing: 0,
      lineHeight: 1,
      fontName: "Roboto",
      rotate: 0,
      verticalAlignment: "top",
      fontColor: "#000000",
      backgroundColor: "",
    },
    remark: {
      type: "text",
      position: {
        x: 116.68,
        y: 84.93,
      },
      width: 79.45,
      height: 23.67,
      alignment: "left",
      fontSize: 10,
      characterSpacing: 0,
      lineHeight: 1,
      fontName: "Roboto",
      rotate: 0,
      verticalAlignment: "top",
      fontColor: "#000000",
      backgroundColor: "",
    },
    country2: {
      type: "text",
      position: {
        x: 140.23,
        y: 44.98,
      },
      width: 35,
      height: 6.21,
      alignment: "center",
      fontSize: 11,
      characterSpacing: 0,
      lineHeight: 1,
      fontName: "Roboto",
      verticalAlignment: "bottom",
      dynamicFontSize: {
        min: 8,
        max: 12,
        fit: "vertical",
      },
    },
    country1: {
      type: "text",
      position: {
        x: 140.5,
        y: 32.02,
      },
      width: 35,
      height: 5.67,
      alignment: "center",
      fontSize: 13,
      characterSpacing: 0,
      lineHeight: 1,
      fontName: "Roboto",
      verticalAlignment: "bottom",
      dynamicFontSize: {
        min: 8,
        max: 14,
        fit: "vertical",
      },
    },
    cert_num: {
      type: "text",
      position: {
        x: 138.12,
        y: 13.23,
      },
      width: 55.9,
      height: 5.4,
      alignment: "left",
      fontSize: 10,
      characterSpacing: 0,
      lineHeight: 1,
      fontName: "Roboto",
      verticalAlignment: "bottom",
    },
    exporter_name: {
      type: "text",
      position: {
        x: 25.4,
        y: 16.15,
      },
      width: 84.73,
      height: 9.37,
      alignment: "left",
      fontSize: 10,
      characterSpacing: 0,
      lineHeight: 1,
      fontName: "Roboto",
      rotate: 0,
      verticalAlignment: "bottom",
      fontColor: "#000000",
      backgroundColor: "",
    },
    destination_country: {
      type: "text",
      position: {
        x: 158.49,
        y: 67.74,
      },
      width: 39.16,
      height: 12.1,
      rotate: 0,
      alignment: "center",
      verticalAlignment: "middle",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
      dynamicFontSize: {
        min: 8,
        max: 12,
        fit: "vertical",
      },
    },
    orig_country: {
      type: "text",
      position: {
        x: 115.36,
        y: 68.27,
      },
      width: 40.5,
      height: 11.05,
      rotate: 0,
      alignment: "center",
      verticalAlignment: "middle",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
      dynamicFontSize: {
        min: 8,
        max: 12,
        fit: "vertical",
      },
    },
    goods: {
      type: "text",
      position: {
        x: 24.87,
        y: 121.02,
      },
      width: 113.52,
      height: 111.85,
      rotate: 0,
      alignment: "left",
      verticalAlignment: "top",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    goods_mass: {
      type: "text",
      position: {
        x: 143.93,
        y: 121.01,
      },
      width: 25.69,
      height: 112.12,
      rotate: 0,
      alignment: "left",
      verticalAlignment: "top",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    invoices: {
      type: "text",
      position: {
        x: 172.36,
        y: 120.97,
      },
      width: 25.67,
      height: 112.11,
      rotate: 0,
      alignment: "left",
      verticalAlignment: "top",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    decl_date_place: {
      type: "text",
      position: {
        x: 125.67,
        y: 261.51,
      },
      width: 67.74,
      height: 5.22,
      rotate: 0,
      alignment: "right",
      verticalAlignment: "bottom",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    decl_name: {
      type: "text",
      position: {
        x: 125.95,
        y: 275.52,
      },
      width: 68.01,
      height: 5.22,
      rotate: 0,
      alignment: "right",
      verticalAlignment: "bottom",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    exporter_addr: {
      type: "text",
      position: {
        x: 25.41,
        y: 26.99,
      },
      width: 84.68,
      height: 16.35,
      rotate: 0,
      alignment: "left",
      verticalAlignment: "top",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    customs: {
      type: "text",
      position: {
        x: 39.94,
        y: 251.71,
      },
      width: 69.61,
      height: 4.44,
      rotate: 0,
      alignment: "left",
      verticalAlignment: "bottom",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    dst_name: {
      type: "text",
      position: {
        x: 25.09,
        y: 49.7,
      },
      width: 84.73,
      height: 9.37,
      alignment: "left",
      fontSize: 10,
      characterSpacing: 0,
      lineHeight: 1,
      fontName: "Roboto",
      rotate: 0,
      verticalAlignment: "bottom",
      fontColor: "#000000",
      backgroundColor: "",
    },
    dst_addr: {
      type: "text",
      position: {
        x: 25.1,
        y: 60.54,
      },
      width: 84.68,
      height: 16.35,
      rotate: 0,
      alignment: "left",
      verticalAlignment: "top",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    ce_date_place: {
      type: "text",
      position: {
        x: 34.33,
        y: 272.56,
      },
      width: 59.27,
      height: 5.22,
      rotate: 0,
      alignment: "left",
      verticalAlignment: "bottom",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
    ce_name: {
      type: "text",
      position: {
        x: 25.35,
        y: 277.37,
      },
      width: 68.01,
      height: 5.22,
      rotate: 0,
      alignment: "right",
      verticalAlignment: "bottom",
      fontSize: 10,
      lineHeight: 1,
      characterSpacing: 0,
      fontColor: "#000000",
      backgroundColor: "",
      fontName: "Roboto",
    },
  },
];
